[workspace]
authors = ["Sean Freeman <sean.freeman@uah.edu>"]
channels = ["conda-forge"]
name = "uah_aes408_508_sp26_public"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.4.0,<3"
matplotlib = ">=3.10.8,<4"
pip = ">=25.3,<26"
ipykernel = ">=7.1.0,<8"
xarray = ">=2025.12.0,<2026"
cartopy = ">=0.25.0,<0.26"
folium = ">=0.20.0,<0.21"
